import time
from selenium import webdriver
driver = webdriver.Chrome()
driver.maximize_window()
driver.get("https://practice.automationtesting.in/")
my_account = driver.find_element_by_id('menu-item-50').click()
name = driver.find_element_by_id('username')
name.send_keys('Egorovegor71@mail.ru')
password = driver.find_element_by_id('password')
password.send_keys('123456qswA!!!')
Shop = driver.find_element_by_id('menu-item-40').click()
time.sleep(3)
driver.execute_script("window.scrollBy(0, 300);")
time.sleep(3)
Javascript_book = driver.find_element_by_tag_name('[data-product_id="165"]').click()
time.sleep(3)
basket = driver.find_element_by_id('wpmenucartli').click()
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium import webdriver
proced_checkout = WebDriverWait(driver, 5).until(
    EC.element_to_be_clickable((By.CSS_SELECTOR, ".checkout-button.button.alt.wc-forward")) )
proced_checkouts = driver.find_element_by_css_selector('.checkout-button.button.alt.wc-forward').click()
first_name = WebDriverWait(driver, 5).until(
    EC.element_to_be_clickable((By.CSS_SELECTOR, ".woocommerce-billing-fields #billing_first_name")))
first_name.send_keys('Egor')
last_name = driver.find_element_by_id('billing_last_name')
last_name.send_keys('Egorov')
company = driver.find_element_by_id('billing_company')
company.send_keys('Be Tester the Best')
email = driver.find_element_by_id('billing_email')
email.send_keys('Egorovegor71@mail.ru')
phone = driver.find_element_by_id('billing_phone')
phone.send_keys('89998880909')
country = driver.find_element_by_id('s2id_billing_country').click()
country_search = driver.find_element_by_id('s2id_autogen1_search')
country_search.send_keys('russia')
Russia_btn = driver.find_element_by_id('select2-results-1').click()
address = driver.find_element_by_id('billing_address_1')
address.send_keys('Prospekt mira 10')
number_apartament = driver.find_element_by_tag_name('[name="billing_address_2"]')
number_apartament.send_keys('15')
city = driver.find_element_by_tag_name('[name="billing_city"]')
city.send_keys('Moscow')
state = driver.find_element_by_tag_name('[name="billing_state"]')
state.send_keys('Moscowskaya')
index = driver.find_element_by_tag_name('[name="billing_postcode"]')
index.send_keys('129343')
time.sleep(2)
driver.execute_script("window.scrollBy(0, 600);")
checkbox_payment = driver.find_element_by_id('payment_method_cheque').click()
place_order = driver.find_element_by_id('place_order').click()
Text_1 = WebDriverWait(driver, 20)
Text_1.until(EC.text_to_be_present_in_element((By.CSS_SELECTOR, ".page-content.entry-content .woocommerce-thankyou-order-received"), "Thank you. Your order has been received."))
Text_2 = WebDriverWait(driver, 20)
Text_2.until(EC.text_to_be_present_in_element((By.CSS_SELECTOR, ".shop_table.order_details tfoot  tr:nth-child(3)"), "Check Payments"))

